config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get '/' => 'videos#index'
  
  post '/videos/:video_id/comments' => 'comments#create'
  resources :videos 
  get '/categories/:name' => 'categories#show_videos'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :video_categories
	has_many :videos, through: :video_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :video
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :title, :url, presence: true
	# ratyrate_rateable "rating"
	# Validate the format of the URL
	has_many :comments
	has_many :video_categories
	has_many :categories, through: :video_categories
end

app/models/video_category.rb
class VideoCategory < ActiveRecord::Base
	belongs_to :video 
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show_videos
		@category = Category.find_by(name: params[:name].capitalize)
		@videos = @category.videos
		render 'show_videos'
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@video = Video.find_by(id: params[:video_id])
		@comment = @video.comments.new(comment_params)
		if @comment.save
			render json: @comment
		else
			# render 'videos/show'
		end
	end

	private 

	def comment_params
		params.require(:comment).permit(:author, :content)
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def index
		@videos = Video.all
		render 'index'
	end

	def new
		# Displaying a form
		render 'new'
	end

	def show
		@video = Video.find_by(id: params[:id])
		@comments = @video.comments
		render 'show'
	end

	def edit
		@video = Video.find_by(id: params[:id])
		render 'edit'
	end

	def create
		@video = Video.new(video_params)
		if @video.save
			redirect_to '/'
		else
			render 'new'
		end
	end
	def update
		@video = Video.find_by(id: params[:id])
		if @video.update(video_params)
			redirect_to '/'
		else
			render 'edit'
		end
	end

	def destroy
		@video = Video.find_by(id: params[:id])
		@video.destroy
		redirect_to '/'
	end

	private

	def video_params
		params.require(:video).permit(:title, :url, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/show_videos.html.erb
<h1> Listing videos for <%= @category.name %> </h1>
<ul>
	<% @videos.each do | video | %>
		<li>
			<h4><%= video.title  %></h4>
			<video src="<%= video.url %>" controls></video>
		</li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YooTube</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/edit.html.erb
<%= form_for @video do | f | %>
	<%= f.label :title %>
	<br>
	<%= f.text_field :title  %>
	<br>
	<%= f.label :url %>
	<br>
	<%= f.text_field :url %>
	<br>
	<%= f.label :description %>
	<br>
	<%= f.text_area :description %>
	<br>
	<!-- <a href="/videos/new"><button>Go to the new video page</button></a> -->
	<%= f.submit  %>
<% end %>

app/views/videos/index.html.erb
<h1>Welcome to the videos index</h1>
<%= link_to('Add New Video', new_video_path) %>

<% @videos.each do | video | %>
	<h4><%= link_to(video.title, video_path(video))%></h4>
	<small><%= link_to('Delete Video', video_path(video), method: "DELETE", data: { confirm: "Are you sure?" }) %></small>
	<!-- <a data-method="DELETE" href="/videos/<%= video.id %>">Delete Video</a> -->
	<!-- <a href="/videos/<%= video.id %>/edit"><%= video.title %></a> -->
	<video src="<%= video.url %>" controls></video>
<% end %>

app/views/videos/new.html.erb
<form action="/videos" method="POST">

  <div>
	<label for="video-title">Title</label>
	<br>
	<input id="video-title" type="text" name="video[title]">
  </div>

  <div>	
	<label for="video-url">URL</label>
	<br>
	<input id="video-url" type="text" name="video[url]">
  </div>

  <div>
	<label for="video-description">Description</label>
	<br>
	<textarea id="video-description" type="text" name="video[description]"></textarea>
	<br>
  </div>
  
	<input type="hidden" name="authenticity_token" 
	 value="<%= form_authenticity_token %>">
	<button type="submit">Create Video</button>
</form>

app/views/videos/show.html.erb
<h4><%= link_to(@video.title, video_path(@video))%></h4>
<video src="<%= @video.url %>" controls></video>
<p>
	<%= @video.description %>
</p>

<form data-id="<%= @video.id %>" class="js-video-comment-form" action="/videos/<%= @video.id %>/comments" method="POST">
	<label for="video-comment-author">Author</label>
	<br>
	<input type="text" id="video-comment-author" name="comment[author]">
	<br>s
	<label for="video-comment-content">Enter your comment</label>
	<br>
	<textarea rows="10" cols="40" type="text" id="video-comment-content" name="comment[content]"></textarea>
	<br>
	<button type="submit">Submit Comment</button>
</form>

<ul class="comment-list">
	<% @comments.each do | comment |  %>
		<li>
			<strong><%= comment.author %> says: </strong>
			<br>
			<p>
			  <%= comment.content %>
			</p>
		</li>
	<% end %>
</ul>